import "/node_modules/flag-icons/css/flag-icons.min.css";

const currencyInfo = [
  {
    id: 1,
    flag: <span className="fi fi-bd"></span>,
    currencyCode: "BDT",
    currencyName: "Bangladeshi Taka",
    countryName: "Bangladesh",
  },
  {
    id: 2,
    flag: <span className="fi fi-us"></span>,
    currencyCode: "USD",
    currencyName: "United States Dollar",
    countryName: "United States",
  },
  {
    id: 3,
    flag: <span className="fi fi-ca"></span>,
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    countryName: "Canada",
  },
  {
    id: 4,
    flag: <span className="fi fi-gb"></span>,
    currencyCode: "GBP",
    currencyName: "British Pound Sterling",
    countryName: "United Kingdom",
  },
  {
    id: 5,
    flag: <span className="fi fi-eu"></span>,
    currencyCode: "EUR",
    currencyName: "Euro",
    countryName: "European Union",
  },
  {
    id: 6,
    flag: <span className="fi fi-jp"></span>,
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    countryName: "Japan",
  },
  {
    id: 7,
    flag: <span className="fi fi-in"></span>,
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    countryName: "India",
  },
  {
    id: 8,
    flag: <span className="fi fi-cn"></span>,
    currencyCode: "CNY",
    currencyName: "Chinese Yuan",
    countryName: "China",
  },
  {
    id: 9,
    flag: <span className="fi fi-au"></span>,
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    countryName: "Australia",
  },
  {
    id: 10,
    flag: <span className="fi fi-br"></span>,
    currencyCode: "BRL",
    currencyName: "Brazilian Real",
    countryName: "Brazil",
  },
  {
    id: 11,
    flag: <span className="fi fi-ru"></span>,
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    countryName: "Russia",
  },
  {
    id: 12,
    flag: <span className="fi fi-kr"></span>,
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    countryName: "South Korea",
  },
  {
    id: 13,
    flag: <span className="fi fi-za"></span>,
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    countryName: "South Africa",
  },
  {
    id: 14,
    flag: <span className="fi fi-mx"></span>,
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    countryName: "Mexico",
  },
  {
    id: 15,
    flag: <span className="fi fi-sg"></span>,
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    countryName: "Singapore",
  },
  {
    id: 16,
    flag: <span className="fi fi-se"></span>,
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    countryName: "Sweden",
  },
  {
    id: 17,
    flag: <span className="fi fi-ch"></span>,
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    countryName: "Switzerland",
  },
  {
    id: 18,
    flag: <span className="fi fi-nz"></span>,
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    countryName: "New Zealand",
  },
  {
    id: 19,
    flag: <span className="fi fi-id"></span>,
    currencyCode: "IDR",
    currencyName: "Indonesian Rupiah",
    countryName: "Indonesia",
  },
  {
    id: 20,
    flag: <span className="fi fi-th"></span>,
    currencyCode: "THB",
    currencyName: "Thai Baht",
    countryName: "Thailand",
  },
  {
    id: 21,
    flag: <span className="fi fi-ar"></span>,
    currencyCode: "ARS",
    currencyName: "Argentine Peso",
    countryName: "Argentina",
  },
  {
    id: 22,
    flag: <span className="fi fi-tr"></span>,
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    countryName: "Turkey",
  },
  {
    id: 23,
    flag: <span className="fi fi-my"></span>,
    currencyCode: "MYR",
    currencyName: "Malaysian Ringgit",
    countryName: "Malaysia",
  },
  {
    id: 24,
    flag: <span className="fi fi-pl"></span>,
    currencyCode: "PLN",
    currencyName: "Polish Złoty",
    countryName: "Poland",
  },
  {
    id: 25,
    flag: <span className="fi fi-hu"></span>,
    currencyCode: "HUF",
    currencyName: "Hungarian Forint",
    countryName: "Hungary",
  },

  {
    id: 27,
    flag: <span className="fi fi-dk"></span>,
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    countryName: "Denmark",
  },
  {
    id: 28,
    flag: <span className="fi fi-no"></span>,
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    countryName: "Norway",
  },
  {
    id: 29,
    flag: <span className="fi fi-cz"></span>,
    currencyCode: "CZK",
    currencyName: "Czech Koruna",
    countryName: "Czech Republic",
  },
  {
    id: 30,
    flag: <span className="fi fi-eg"></span>,
    currencyCode: "EGP",
    currencyName: "Egyptian Pound",
    countryName: "Egypt",
  },
  {
    id: 31,
    flag: <span className="fi fi-ph"></span>,
    currencyCode: "PHP",
    currencyName: "Philippine Peso",
    countryName: "Philippines",
  },
  {
    id: 32,
    flag: <span className="fi fi-ae"></span>,
    currencyCode: "AED",
    currencyName: "United Arab Emirates Dirham",
    countryName: "United Arab Emirates",
  },
  {
    id: 33,
    flag: <span className="fi fi-za"></span>,
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    countryName: "South Africa",
  },
  {
    id: 34,
    flag: <span className="fi fi-sa"></span>,
    currencyCode: "SAR",
    currencyName: "Saudi Riyal",
    countryName: "Saudi Arabia",
  },
  {
    id: 35,
    flag: <span className="fi fi-qa"></span>,
    currencyCode: "QAR",
    currencyName: "Qatari Riyal",
    countryName: "Qatar",
  },
  {
    id: 36,
    flag: <span className="fi fi-kw"></span>,
    currencyCode: "KWD",
    currencyName: "Kuwaiti Dinar",
    countryName: "Kuwait",
  },
  {
    id: 37,
    flag: <span className="fi fi-ng"></span>,
    currencyCode: "NGN",
    currencyName: "Nigerian Naira",
    countryName: "Nigeria",
  },
  {
    id: 38,
    flag: <span className="fi fi-ke"></span>,
    currencyCode: "KES",
    currencyName: "Kenyan Shilling",
    countryName: "Kenya",
  },
  {
    id: 39,
    flag: <span className="fi fi-vn"></span>,
    currencyCode: "VND",
    currencyName: "Vietnamese Đồng",
    countryName: "Vietnam",
  },
  {
    id: 40,
    flag: <span className="fi fi-cl"></span>,
    currencyCode: "CLP",
    currencyName: "Chilean Peso",
    countryName: "Chile",
  },
];

export default currencyInfo;
